language: python
python: 
  - "3.6.4"
services:
  - postgresql
before_install: 
  - psql -c 'create database flask_api;' -U postgres
  - psql -c 'create database test_db;' -U postgres
install: 
  - "export FLASK_APP=\"run.py\""
  - "export SECRET=\"some-very-long-string-of-random-characters-CHANGE-TO-YOUR-LIKING\""
  - "export APP_SETTINGS=\"development\""
  - "export DATABASE_URL=\"postgresql://postgres@localhost/flask_api\""
  - "pip install -r requirements.txt"
  - "python manage.py db upgrade"
script: "pytest"